# Generated by Django 4.2.4 on 2023-09-22 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0003_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_registration',
            old_name='gests',
            new_name='guests',
        ),
        migrations.AddField(
            model_name='events',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='event_atendees', to='ActivityEvents.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 9, 22), null=True),
        ),
    ]
