# Generated by Django 4.2.3 on 2023-10-04 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0004_alter_event_registration_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 10, 4), null=True),
        ),
    ]
