# Generated by Django 4.2.3 on 2023-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0006_contact_us_alter_event_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
