# Generated by Django 4.2.3 on 2023-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0007_alter_event_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
