# Generated by Django 4.2.4 on 2023-09-28 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0008_alter_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='atendees',
        ),
        migrations.RemoveField(
            model_name='events',
            name='creator',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 9, 28), null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
