# Generated by Django 4.2.4 on 2023-09-30 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0009_remove_event_registration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 9, 30), null=True),
        ),
    ]
