# Generated by Django 4.2.3 on 2023-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0011_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peoplereviews',
            name='description',
            field=models.TextField(),
        ),
    ]
